version: '3'
services:
  web:
    build: .
    image: "auth"
    ports:
     - "4200:4200"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
